version: '3.4'

services:
    postgres:
        image: postgres:latest
        container_name: postgres-scd2
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=productDb
        ports: 
            - "5432:5432"
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-scd2
        environment: 
            - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=pgadmin
        ports:
            - '5050:80'
        restart: always
